server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jefferson1995/ead-config-server-repo
          default-label: main
          username: jefferson1995
          password: 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

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

